name = "helios"
main = "src/index.ts"
compatibility_date = "2023-10-30"

[observability]
enabled = true

[[d1_databases]]
binding = "dev_pmo"
database_name = "dev-pmo"
database_id = "600647f9-8709-471a-b497-b6c1f3f4de9c"

[durable_objects]
bindings = [
  { name = "PROJECT_ACTOR", class_name = "ProjectActor" }
]

[[migrations]]
tag = "v1"
new_classes = ["ProjectActor"]
